"""add moteur role

Revision ID: 00bb5125002f
Revises: 8ed77cdaf56c
Create Date: 2024-05-23 17:50:50.860490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bb5125002f'
down_revision: Union[str, None] = '8ed77cdaf56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_moteur',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_title', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'member_id'], ['contributor.project_id', 'contributor.member_id'], ),
    sa.ForeignKeyConstraint(['project_id', 'task_title'], ['task.project_id', 'task.title'], ),
    sa.PrimaryKeyConstraint('project_id', 'task_title', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_moteur')
    # ### end Alembic commands ###
