"""Initial db model

Revision ID: d5882b316093
Revises: 
Create Date: 2024-02-25 13:37:28.376188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5882b316093'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_connexion',
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('gtoken', sa.String(), nullable=True),
    sa.Column('gmail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_table('user_access',
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('thing_id', sa.String(), nullable=False),
    sa.Column('mention', sa.String(), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_connexion.server_id'], ),
    sa.PrimaryKeyConstraint('server_id', 'thing_id')
    )
    op.create_table('watched_calendar',
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('watch_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('filter', sa.String(), nullable=True),
    sa.Column('updates_new', sa.Integer(), nullable=True),
    sa.Column('updates_mod', sa.Integer(), nullable=True),
    sa.Column('updates_del', sa.Integer(), nullable=True),
    sa.Column('replace', sa.String(), nullable=True),
    sa.Column('calendar_id', sa.String(), nullable=True),
    sa.Column('calendar_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server_connexion.server_id'], ),
    sa.PrimaryKeyConstraint('server_id', 'watch_id')
    )
    op.create_table('event_summary',
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('watch_id', sa.String(), nullable=False),
    sa.Column('summary_id', sa.String(), nullable=False),
    sa.Column('base_date', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id', 'watch_id'], ['watched_calendar.server_id', 'watched_calendar.watch_id'], ),
    sa.PrimaryKeyConstraint('server_id', 'watch_id', 'summary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_summary')
    op.drop_table('watched_calendar')
    op.drop_table('user_access')
    op.drop_table('server_connexion')
    # ### end Alembic commands ###
