"""add project main thread

Revision ID: 15cc3db8cb54
Revises: 5ca6eeb75af9
Create Date: 2024-03-09 20:36:01.699484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cc3db8cb54'
down_revision: Union[str, None] = '5ca6eeb75af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('main_thread', sa.String(), nullable=True))
    op.add_column('project', sa.Column('main_message', sa.String(), nullable=True))
    op.add_column('project', sa.Column('sec_messages', sa.String(), nullable=True))
    op.add_column('project', sa.Column('main_template', sa.String(), nullable=True))
    op.add_column('project', sa.Column('sec_template', sa.String(), nullable=True))
    op.add_column('project', sa.Column('reminder_template', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'reminder_template')
    op.drop_column('project', 'sec_template')
    op.drop_column('project', 'main_template')
    op.drop_column('project', 'sec_messages')
    op.drop_column('project', 'main_message')
    op.drop_column('project', 'main_thread')
    # ### end Alembic commands ###
