"""add admin field to contributor table

Revision ID: 5ca6eeb75af9
Revises: 7f8b19f2ad1e
Create Date: 2024-03-07 01:08:28.279432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca6eeb75af9'
down_revision: Union[str, None] = '7f8b19f2ad1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributor', sa.Column('project_admin', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributor', 'project_admin')
    # ### end Alembic commands ###
