"""add timezone field for a server

Revision ID: 8ed77cdaf56c
Revises: a1b74a00adfe
Create Date: 2024-03-11 12:54:25.905440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed77cdaf56c'
down_revision: Union[str, None] = 'a1b74a00adfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_connexion', sa.Column('timezone', sa.String(), nullable=False, server_default="UTC"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_connexion', 'timezone')
    # ### end Alembic commands ###
